module.exports = {
    login: 'mavarona',
    id: 13487993,
    node_id: 'MDQ6VXNlcjEzNDg3OTkz',
    avatar_url: 'https://avatars2.githubusercontent.com/u/13487993?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mavarona',
    html_url: 'https://github.com/mavarona',
    followers_url: 'https://api.github.com/users/mavarona/followers',
    following_url: 'https://api.github.com/users/mavarona/following{/other_user}',
    gists_url: 'https://api.github.com/users/mavarona/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/mavarona/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/mavarona/subscriptions',
    organizations_url: 'https://api.github.com/users/mavarona/orgs',
    repos_url: 'https://api.github.com/users/mavarona/repos',
    events_url: 'https://api.github.com/users/mavarona/events{/privacy}',
    received_events_url: 'https://api.github.com/users/mavarona/received_events',
    type: 'User',
    site_admin: false,
    name: 'Miguel Ángel',
    company: 'Conquistadores de lo inútil',
    blog: '',
    location: 'Madrid',
    email: null,
    hireable: null,
    bio: null,
    public_repos: 21,
    public_gists: 0,
    followers: 0,
    following: 0,
    created_at: '2015-07-24T18:27:35Z',
    updated_at: '2019-05-18T09:52:18Z'
};